README.rst

Fix package name transition year date.

DOC: Fix package name transition year date

---

.maint/update_authors.py
scripts/optimize_registration.py
src/nifreeze/conftest.py
src/nifreeze/estimator.py
test/conftest.py

Hopefully fixing issues that have very recently emerged.

STY: Run latest version of *ruff*

---

.github/workflows/test.yml
README.rst
src/nifreeze/registration/ants.py
src/nifreeze/testing/simulations.py

- ENH: Run the `codespell` spell checker in CI
- DOC: Fix spelling mistakes detected by `codespell`

DOC: Fix spelling mistakes detected by `codespell`

---

src/nifreeze/model/__init__.py
src/nifreeze/model/base.py
src/nifreeze/model/dmri.py
test/test_model.py

- STYLE: Increase consistency in average DWI model class name
- DOC: Honor the purpose of the average DWI model in class docstring

STYLE: Increase consistency in average DWI model class name

---

src/nifreeze/model/base.py
test/test_model.py

- ENH: Provide masks to models in tests
- BUG: Fill mask parameter for trivial model in model factory

ENH: Provide masks to models in tests

---

src/nifreeze/data/filtering.py
src/nifreeze/data/pet.py
src/nifreeze/data/splitting.py
src/nifreeze/estimator.py
src/nifreeze/model/__init__.py
src/nifreeze/model/base.py
src/nifreeze/model/pet.py
test/test_registration.py

Remove year from copyright notice following
https://github.com/nipreps/eddymotion/pull/235/commits/3f6692701d3971339b24e1ad6bc97e4396b2e40a

DOC: Remove year from copyright notice

---

src/nifreeze/data/dmri.py
src/nifreeze/data/filtering.py
src/nifreeze/model/dmri.py

- DOC: Add missing parameter docstrings
- DOC: Fix grammar in docstring
- DOC: Mark optional parameters as such
- DOC: Fix typo in docstring

DOC: Miscellaneous improvements to documentation

---

.github/workflows/test.yml
pyproject.toml
src/nifreeze/data/base.py
src/nifreeze/estimator.py
test/test_data_base.py
tox.ini

fix: Test on Python 3.10+, use typing_extensions backports

---

docs/developers.rst
src/nifreeze/analysis/measure_agreement.py
src/nifreeze/viz/bland_altman.py
test/test_analysis.py
test/test_viz_bland_altman.py

Add Bland-Altman plot function.
Includes the ability to highlight N lower and upper extreme values along the X axis.

ENH: Add Bland-Altman plot function

---

src/nifreeze/analysis/measure_agreement.py
src/nifreeze/viz/bland_altman.py
test/test_viz_bland_altman.py

Identify Bland-Altman salient points.

ENH: Identify Bland-Altman salient points

---

scripts/fetch_fmri_nb_openneuro_data.sh

Add script to fetch fMRI notebook data.

ENH: Add script to fetch fMRI notebook data

---

src/nifreeze/cli/parser.py
src/nifreeze/cli/run.py
src/nifreeze/data/base.py
src/nifreeze/estimator.py
src/nifreeze/model/base.py
test/test_main.py
test/test_parser.py

Ensures the CLI can load a NIfTI/h5 file and run the average model.

FIX: Streamline the most basic usecase (bold data)

---

.github/workflows/notebooks.yml
tools/run_notebooks.py

- TST: Install `datalad` in notebook run GHA workflow
- STYLE: Prefer downloading the data for notebooks in GHA workflow file
- TST: Allow triggering the notebook GHA workflow run manually

TST: Fix notebook run GHA workflow

---

.github/workflows/notebooks.yml

- TST: Streamline notebook CI workflow file with main CI workflow file
- TST: Set the testing data home environment variable in notebook CI
- TST: Download data from G-Node GIN in notebook testing GHA workflow

TST: Download data from G-Node GIN in notebook testing GHA workflow

---

CITATION.cff

Add `CITATION.cff` file with the ISMRM 2025 abstract reference.

DOC: Add `CITATION.cff` file with ISMRM 2025 abstract reference

---

src/nifreeze/analysis/measure_agreement.py
test/test_analysis.py

- ENH: Fix Bland-Altman plot salient data identification
- ENH: Ensure BA data point sufficiency for salient point identification
- DOC: Fix description of identified right-most BA plot data points
Fixes #92.

ENH: Fix Bland-Altman plot salient data identification

---

src/nifreeze/analysis/filtering.py
src/nifreeze/analysis/motion.py
test/test_analysis.py

Add framewise displacement peak detection function.

ENH: Add framewise displacement peak detection function

---

.zenodo.json
README.rst
pyproject.toml

Increase consistency in package description:
- Use the same description across the `README.rst`, `pyproject.toml`, and `.zenodo.json` files. Especially, update the description field in the `pyproject.toml` to honor the current vision of the tool.
- Adopt a title that best honors the current vision of the tool in the corresponding field of the `.zenodo.json` file, and adopt it in the `README.rst` file before the description.

DOC: Increase consistency in package description

---

src/nifreeze/model/pet.py

I simplified the model interface after the refactor in #62.

FIX: Revise interface and implementation of PET model

---

src/nifreeze/model/pet.py

Amends a lazy decision in #139.

FIX: Roll back removal of brainmask in #139

---

scripts/fetch_pet_nb_gin_data.sh
scripts/simulate_pet_motion_data.py

This PR closes issue #145 by adding fetching of PET data and simulation of motion corrupted PET data. Separated out from #88.

ENH: add scripts to fetch and simulate PET data

---

pyproject.toml
src/nifreeze/data/filtering.py
src/nifreeze/registration/ants.py
test/conftest.py
test/test_filtering.py

- STY: Rename n-dimensional data generation fixture
- ENH: Allow `advanced_clip` to be performed in-place

ENH: Allow `advanced_clip` to be performed in-place

---

src/nifreeze/viz/motion_viz.py

Remove dash from "frame-wise":
https://dictionary.cambridge.org/us/dictionary/english/wise

DOC: Remove dash from "frame-wise"

---

src/nifreeze/model/dmri.py

- DOC: Increase consistency in dMRI model init docstring
- DOC: Fix grammar in dMRI model comment

DOC: Improve dMRI model documentation style

---

docs/notebooks/pet_motion_estimation.ipynb

- FIX: Remove model argument from the PET motion estimator instantiation
- FIX: Remove unexpected n_jobs kwarg in PET estimator instantiation

FIX: Fix miscellaneous errors in the PET notebook

---

.github/workflows/test.yml
pyproject.toml

- TST: Reuse the `TEST_DATA_HOME` env variable in GHA test workflow
- REF: Remove the outdated PET notebook from `ruff` exclusion list
- STY: Remove unnecessary empty lines in `pyproject.toml` file
- REF: Remove non-relevant files from codespell skip list
- STY: Use two spaces for indentation in `pyproject.toml` consistently
- STY: Use double quotation marks in `pyproject.toml` consistently

STY: Miscellaneous cleanup

---

docs/installation.rst

Remove unnecessary blank line at the top of the file. Increases consistency across the documentation files.

STY: Remove unnecessary blank line at the top of the file

---

docs/notebooks/pet_motion_estimation.ipynb

Remove unused variable in PET notebook: left behind in commit 0357331.

REF: Remove unused variable in PET notebook

---

test/test_data_utils.py

Add license header to data utils testing file.

DOC: Add license header to data utils testing file

---

test/test_data_utils.py

Exercise writing the transformed NIfTI data to a file in the `apply_affines` function.

TST: Exercise writing the transformed NIfTI data to a file

---

test/test_model.py

Test instantiating the dMRI models through the factory.

TST: Test dMRI model instantiation through factory

---

test/test_estimator.py

Add estimator module unit test.
Test that the estimator deals correctly with model instances.

TST: Add estimator module unit test

---

src/nifreeze/data/pet.py

Mark optional argument as such in PET function.

DOC: Mark optional argument as such in PET function

---

test/test_data_pet.py

Zero out the earliest time in PET frame time test to match the implementation. Add a new test case to demonstrate it.
Refactor the test to mirror the implementation.

TST: Zero out the earliest time in PET frame time test

---

test/test_estimator.py

Test that the estimator handles correctly instantiating models through the factory when given a model name.
Make the dummy model return a random array instead of an all-ones array as its prediction to avoid the advanced clip function raise invalid value warnings when called by the NIfTI serialization functions of the registration data preparation process. Avoids:
```
test/test_estimator.py::test_estimator_init_model_string
/home/runner/work/nifreeze/nifreeze/src/nifreeze/data/filtering.py:107:
RuntimeWarning: invalid value encountered in divide
data /= data.max()
test/test_estimator.py::test_estimator_init_model_string
/home/runner/work/nifreeze/nifreeze/src/nifreeze/data/filtering.py:113:
RuntimeWarning: invalid value encountered in cast
np.round(255 * data, out=data).astype(dtype)
``` …

TST: Test model instantiation by estimator given name
