docs/notebooks/dwi_gp_estimation.ipynb, scripts/dwi_gp_estimation_signal_plot.py, src/nifreeze/data/utils.py, src/nifreeze/testing/simulations.py, src/nifreeze/utils/ndimage.py, test/test_data_utils.py
Use the same alias consistently to import `nibabel`: prefer using `nb` over `nib` as it is more popular across `nipreps` (used in 273 files vs. 13 as of Jan 8, 2025).
=> STYLE: Use the same alias consistently to import `nibabel`

pyproject.toml
Enforce `flake8` import conventions.
Add `nb` as the unconventional import alias for `nibabel` so that every time `nibabel` needs to be imported it is imported as `nb` consistently.
Documentation:
https://docs.astral.sh/ruff/rules/#flake8-import-conventions-icn
=> STYLE: Enforce `flake8` import conventions

scripts/dwi_gp_estimation_signal_plot.py, src/nifreeze/model/_dipy.py, src/nifreeze/testing/simulations.py
Pass parameters as keyword arguments when calling DIPY functions and methods that have keyword arguments: DIPY has transitioned to keyword-only arguments for these starting version 1.10.0 (released Dec 12, 2024):
https://docs.dipy.org/1.10.0/api_changes.html#dipy-1-10-0-changes
Fixes:
```
src/nifreeze/testing/simulations.py:181:
UserWarning: Pass ['bvecs'] as keyword args.
From version 2.0.0 passing these as positional arguments will result in an error.
return gradient_table(bvals, bvecs)
```
https://github.com/nipreps/nifreeze/actions/runs/12457578962/job/34772277392?pr=35#step:12:1015
=> ENH: Use keyword arguments when calling  DIPY keyword arg functions

src/nifreeze/model/base.py, src/nifreeze/registration/ants.py
Warn users if masks are not provided for registration and model fitting.
Closes #10.
=> ENH: Warn users if masks are not provided for registration and fitting

pyproject.toml
Update minimum required `scikit-learn` version to 1.3.0 (released June 2023):
- 0.18 dates back to Sept 28, 2016 (9 years ago): https://scikit-learn.org/1.6/whats_new/v0.18.html#changes-0-18
- CI testing is using 1.6.0, the most recent version to date: https://scikit-learn.org/1.6/whats_new/v1.6.html
- Following the errors discovered during the type hinting efforts, the `DiffusionGPR` class is accepting the `n_targets` named parameter constraint, which was introduced in `scikit-learn` version 1.3.0: https://scikit-learn.org/1.6/whats_new/v1.3.html#sklearn-gaussian-process
Documentation:
https://scikit-learn.org/1.6/whats_new/v1.3.html#version-1-3-0
=> MAINT: Update minimum required `scikit-learn` version to 1.3.0

pyproject.toml
Bump dependencies versions that support Python 3.10, which is the minimum version `NiFreeze` requires:
- `DIPY` 1.5.0 is the first version supporting Python 3.10: https://github.com/dipy/dipy/blob/009c6fe781016370577fa052eee3c26bd25fbd10/doc/old_highlights.rst#older-highlights
- `NumPy` 1.21.3 is the first version supporting Python 3.10: https://numpy.org/doc/stable/release/1.21.3-notes.html#numpy-1-21-3-release-notes
- Users of Python 3.5 or later should be using `scikit-image` 0.15.x or later: https://github.com/scikit-image/scikit-image/blob/main/doc/source/release_notes/release_0.14.rst#scikit-image-0144-2019-09-04
=> MAINT: Bump dependencies versions that support Python 3.10

src/nifreeze/data/splitting.py, src/nifreeze/estimator.py, test/test_integration.py, test/test_model.py, test/test_splitting.py
Leverage the new ``__getitem__`` interface, which provides uniform indexed access across modalities.
Requires: #52.
Related-To: #19.
Resolves: #20.
=> ENH: Update LOVO splitter to new dataset indexed access

.github/workflows/benchmark.yml, benchmarks/README.rst, benchmarks/asv.conf.json, benchmarks/benchmarks/bench_model.py, pyproject.toml
Add benchmarking files so that `nifreeze` can be benchmarked using `asv`:
- Add the actual files that allow to benchmark different `nifreeze` capabilities.
- Add a new `benchmark` optional dependencies section to `pyproject.toml`.
- Add the `asv` configuration file.
- Add a `README.rst` file to explain how to run the benchmarking.
- Add a GitHub Actions workflow file to run the benchmarks for every PR.
=> MAINT: Add benchmarking files

.github/workflows/test.yml, docs/conf.py, pyproject.toml, scripts/dwi_gp_estimation_error_analysis.py, scripts/dwi_gp_estimation_error_analysis_plot.py, scripts/dwi_gp_estimation_simulated_signal.py, scripts/optimize_registration.py, src/nifreeze/cli/parser.py, src/nifreeze/data/base.py, src/nifreeze/data/dmri.py, src/nifreeze/data/filtering.py, src/nifreeze/data/pet.py, src/nifreeze/model/_dipy.py, src/nifreeze/model/gpr.py, src/nifreeze/registration/ants.py, src/nifreeze/utils/iterators.py, src/nifreeze/viz/signals.py, test/test_data_base.py, test/test_gpr.py, tox.ini
Add static type checking: use `mypy` to ensure that variable and function calls are using the appropriate types.
Configure and run `mypy` checks in CI, including the spell checking.
Documentation:
https://mypy.readthedocs.io/en/stable/index.html
=> MAINT: Add static type checking

pyproject.toml, src/nifreeze/model/base.py, test/test_model.py
Test absent mask warning: parameterize the trivial model test so that the warning raised for the case where the model is instatiated without a mask can be tested.
Remove the corresponding message from the `filterwarnings` list.
=> ENH: Test absent mask warning

src/nifreeze/utils/iterators.py
- ENH: Add None to b-vals iterators `size` parameter annotations
- ENH: Make `linear_iterator` return an iterator
- ENH: Remove unused parameter form `bvalue_iterator` prototype
=> DOC: Revision of docstrings in the iterators' module

docs/notebooks/bold_realignment.ipynb, scripts/optimize_registration.py, src/nifreeze/cli/run.py, src/nifreeze/data/dmri.py, src/nifreeze/estimator.py, src/nifreeze/model/__init__.py, src/nifreeze/model/_dipy.py, src/nifreeze/model/base.py, src/nifreeze/model/dmri.py, src/nifreeze/registration/ants.py, test/conftest.py, test/test_data_dmri.py, test/test_integration.py, test/test_model.py
Changes our current implementation of the estimator with a new architecture that allows stacking
(https://github.com/nipreps/nifreeze/issues/12#issuecomment-2598471780):
```Python
estimator_level1 = Estimator(model="b0", ...)    # e.g., 6 dof registration
estimator_level2 = Estimator(model="b0", input=estimator_level1, ...) # e.g., 9 dof registration
estimator_level2.fit(dataset_object)  # Checks "input" and it's another estimator, so runs that first
```
This allow for adding *filters* (to be implemented):
``` Python
downsample = Filter(...)  # e.g., downsampling filter
estimator_level1 = Estimator(model="b0", input=downsample, ...)    # e.g., 6 dof registration
estimator_level2 = Estimator(model="b0", input=estimator_level1, ...) # e.g., 9 dof registration …
```
=> ENH: Implicitly-pipelined and modality-agnostic ``Estimator``

tox.ini
Fix `notebooks` testing configuration `env` warning: add the `test` extra to the `notebooks` testing environment so that the `pytest-env` plugin is present.
Fixes:
```
.tox/notebooks/lib/python3.12/site-packages/_pytest/config/__init__.py:1441
PytestConfigWarning: Unknown config option: env
self._warn_or_fail_if_strict(f"Unknown config option: {key}\n")
```
https://github.com/nipreps/nifreeze/actions/runs/12969034501/job/36172649151?pr=72#step:12:1069
=> MAINT: Fix `notebooks` testing configuration `env` warning

src/nifreeze/utils/iterators.py
Use appropriate name for b-values kwarg in iterators: while the docstrings were documenting the `bvalues` keyword argument, the code was checking the presence of the `bvals` name. Use `bvals` in the docstrings.
=> DOC: Use appropriate name for b-values kwarg in iterators

src/nifreeze/data/dmri.py, src/nifreeze/model/base.py, src/nifreeze/model/dmri.py
- ENH: Add type hints across miscellaneous methods
- STYLE: Prefer specifying b-values as integer types
- STYLE: Prefer building an array with `None` to fill `S0`
=> ENH: Add type hints across miscellaneous methods

src/nifreeze/data/dmri.py
- BUG: Use the appropriate index to extract b-values
- STYLE: Add gradient-related properties to DWI data class
- STYLE: Make bvecs/bvals serialized shapes match comments/expectations
- STYLE: Simplify getting the root name for DWI serialization
- DOC: Mark the `insert_b0` parameter as optional
- ENH: Add decimal places for bval/bvec serialization
=> BUG: Use the appropriate index to extract b-values

pyproject.toml, src/nifreeze/model/gpr.py, src/nifreeze/testing/simulations.py, test/conftest.py, test/test_data_base.py, test/test_data_dmri.py, test/test_data_utils.py, test/test_model.py, test/test_splitting.py
- ENH: Prefer using NumPy's random number generator
- STYLE: Use the `GradientTable` class for type hinting
- STYLE: Remove `ClassVar[dict]` type hinting from GPR param constraints
- ENH: Ignore `scikit-learn` `Interval` and `StrOptions` type checking
- MAINT: Require `nitransforms` 22.x
=> ENH: Prefer using NumPy's random number generator

src/nifreeze/data/dmri.py, test/test_data_dmri.py
Add a shell data property to `DWI` data class that returns a list of pairs consisting of the estimated b-value and the associated DWI data.
Closes #66.
=> ENH: Add a shell data property to `DWI` data class

.github/workflows/notebooks.yml, tools/run_notebooks.py, tox.ini
Fix running notebooks:
- Notebooks were being supposedly run within the `test.yml` workflow. However, the fMRI BOLD notebook requires some data to be downloaded from OpenNeuro, and the data was not being downloaded.
- Run the data downloading script within the `notebooks` testing environment in `tox.ini`
- Run notebooks once every week through a cron job in a dedicated workflow file.
- Modify the Python versions being used in the CI `test.yml` file to avoid running the notebooks.
=> FIX: Actually run notebooks on CI

test/test_data_dmri.py
Remove unrelated documentation from test function. The removed documentation corresponds to `test_ANTs_config_b0`.
=> DOC: Remove unrelated documentation from test function

.github/workflows/notebooks.yml
Install `git-annex` for `datalad`.
Fixes:
```
install(error):
/home/runner/work/nifreeze/nifreeze/nifreeze-tests/ds000005 (dataset)
[No working git-annex installation of version >= 8.20200309.
Visit http://handbook.datalad.org/r.html?install
for instructions on how to install DataLad and git-annex.]
Error: Process completed with exit code 1.
```
https://github.com/jhlegarreta/nifreeze/actions/runs/14812843818/job/41589689568#step:6:27
=> TST: Install `git-annex` for `datalad`

.github/workflows/notebooks.yml
Configure `git` user for `datalad` in notebook CI workflow.
=> TST: Configure `git` user for `datalad` in notebook CI workflow

.github/workflows/notebooks.yml
Install the necessary `TeX` packages in the test CI so that `LaTeX` decoration in plots can be employed.
Fixes:
```
FAILED docs/notebooks/data_structures.ipynb::data_structures.ipynb -
RuntimeError: Failed to process string with tex because latex could not be foun
```
and other related errors.
https://github.com/jhlegarreta/nifreeze/actions/runs/14813656376/job/41591480555#step:9:844
=> TST: Install `TeX` packages in notebook workflow

.github/workflows/notebooks.yml
Download dMRI covariance notebook data from OSF instead of using G-Node GIN: the latter is orders of magnitude slower, which is inconvenient to test the notebook.
The data has been previously uploaded to OSF.
Install the `osfclient` in order to effectively download the data.
=> TST: Download dMRI covariance notebook data from OSF

pyproject.toml
Pin `virtualenv` for benchmark environment: the latest `virtualenv` version (v20.31.0) drops the support for the `--wheel=bundle` argument, resulting in following error when running `asv` setup:
```
virtualenv: error: unrecognized arguments: --wheel=bundle
```
https://github.com/nipreps/nifreeze/actions/runs/14895685075/job/41838083838#step:6:46
Solution proposed in the `asv` repository:
https://github.com/airspeed-velocity/asv/issues/1484#issuecomment-2853982396
=> TST: Pin `virtualenv` for benchmark environment

docs/notebooks/bold_realignment.ipynb
Fix FD plot function call in BOLD fMRI realignment notebook: provide the framewise displacement data as a `pandas` `DataFrame` and group the labels for the legend into a list.
Left behind in commit 2d95cbb.
Take advantage of the commit to transfer a lonely `import` statement to the immediately subsequent cell where the actual plot function is called for the sake of compactness and consistency.
=> FIX: Fix FD plot function call in BOLD fMRI realignment notebook

.github/workflows/notebooks.yml
Reorder notebook GHA workflow file steps for improved logic:
1. Set up the action.
2. Install the necessary libraries.
3. Download the data.
4. Install `tox` to be able to run the notebooks.
5. Run the notebooks.
Take advantage of the commit to improve the name of the OSF data download step.
=> STY: Reorder notebook GHA workflow file steps for improved logic

.github/workflows/notebooks.yml
Avoid attempting to create test data directory in notebook GHA workflow file: create testing data directory before starting to download data.
The step where the data from `OpenNeuro` was being downloaded was effectively creating the test data directory and, thus, attempting to create the directory was failinng in the next step, where the data from OSF was bing downloaded, and which included creating the directory.
Fixes:
```
Run mkdir ${TEST_DATA_HOME}
(...)
mkdir: cannot create directory ‘/home/runner/nifreeze-tests/’: File exists
```
raised for example at:
https://github.com/nipreps/nifreeze/actions/runs/15097105297/job/42433228274?pr=117#step:11:19
Inadvertently introduced in commit c170c40.
=> TST: Avoid attempting to create test data directory in notebook GHA

CITATION.cff
Remove "Accepted" note in citation file: the work was presented on May 14 2025.
=> DOC: Remove "Accepted" note in citation file

tools/run_notebooks.py
Increase notebook timeout value: set it to 3600 s (60 minutes; the default value is 300 s).
Fixes:
```
__ /home/runner/work/nifreeze/nifreeze/docs/notebooks/bold_realignment.ipynb ___
A cell timed out while it was being executed, after 300 seconds.
The message was: Cell execution timed out.
```
raised for example at:
https://github.com/nipreps/nifreeze/actions/runs/15102456036/job/42445432169#step:15:43
=> MAINT: Increase notebook timeout value

src/nifreeze/data/__init__.py, src/nifreeze/data/base.py, src/nifreeze/data/dmri.py, src/nifreeze/data/pet.py, src/nifreeze/estimator.py
- DOC: Do not use a dash in the general case of the "head motion" term
- DOC: Honor better purpose in estimator module and class documentation
=> DOC: Miscellaneous improvements to documentation

pyproject.toml, src/nifreeze/data/base.py, src/nifreeze/data/dmri.py, src/nifreeze/data/pet.py
Fix miscellaneous static check failures: transition to the more modern `attrs` API in lieu of `attr`:
- Install the `attrbs` package and the missing type stubs for the `attrs` library.
- Adapt the corresponding properties: use `@attrs.define` instead of `@attr.s`, and `attrs.field` instead of `attr.ib`.
- Add missing annotations for `data.base.BaseDataset` and `data.dmri.DWI` attributes.
Fixes:
```
Cannot find implementation or library stub for module named "attr"
```
and
```
src/nifreeze/data/base.py:32: note: See https://mypy.readthedocs.io/en/stable/running_mypy.html#missing-imports
src/nifreeze/data/pet.py:30: error: Cannot find implementation or library stub for module named "attrs"  [import-not-found]
src/nifreeze/data/pet.py:170: error: Unexpected keyword argument "dataobj" for …
```
=> STY: Fix miscellaneous static check failures

src/nifreeze/cli/parser.py, src/nifreeze/cli/run.py, src/nifreeze/estimator.py, test/test_parser.py
The CLI passes ``njobs``, while DIPY uses ``n_jobs``. This PR unifies the variable name.
=> FIX: Treatment of ``n_jobs`` by estimator

.maint/update_description.py
Add zenodo file project description update script: serves to update the `.zenodo.json` file `description` tag value by copying the value of the same tag in the `pyproject.toml` file. Allows to keep the `.zenodo.json` file in sync.
When copyng the description, it respects any opening/closing HTML tags present in the `.zenodo.json` file; if none is found, it uses the paragraph starting/ending tags.
=> MNT: Add zenodo file project description update script

.maint/update_authors.py
Add dependencies to author update script as a script metadata comment block so that tools like `uv` can create an isolated environment without a full project setup.
=> MNT: Add dependencies to author update script

.maint/update_authors.py
Add license header to author update script.
Take advantage of the commit to remove the Python interpreter shebang line for the sake of consistency across the package and current conventions across the NiPreps projects.
=> STY: Add license header to author update script

src/nifreeze/cli/run.py, src/nifreeze/estimator.py, src/nifreeze/model/base.py, src/nifreeze/model/dmri.py, src/nifreeze/model/pet.py
This allows having "frozen" models that are fit only once before entering the leave-one-out loop.
These models use all the data in the fitting and then return always the same "prediction".
This feature was lost with the refactor of the estimator. By moving it into the models, we can use them in a more flexible way.
=> ENH: Re-allow "locking" of models with first fit

src/nifreeze/registration/ants.py, test/test_registration.py
Use `importlib` instead of `pkg_resources` to retrieve package resource files.
```
src/nifreeze/registration/ants.py:37
src/nifreeze/registration/ants.py:37
/home/runner/work/nifreeze/nifreeze/src/nifreeze/registration/ants.py:37:
UserWarning: pkg_resources is deprecated as an API.
See https://setuptools.pypa.io/en/latest/pkg_resources.html.
The pkg_resources package is slated for removal as early as 2025-11-30.
Refrain from using this package or pin to Setuptools<81.
from pkg_resources import resource_filename as pkg_fn
```
raised for example at:
https://github.com/nipreps/nifreeze/actions/runs/15301631097/job/43043463683#step:11:266
=> MNT: Use `importlib` instead of `pkg_resources` to retrieve files

src/nifreeze/model/gpr.py
Ignore `scikit-learn` `Hyperparameter` class instantiation type check.
According to the version documentation, `name`, `value_type` and `bounds` are positional arguments, and are provided as such. Additionally, `name` and `value_type` are expected to have `str` types, which they do:
https://scikit-learn.org/1.6/modules/generated/sklearn.gaussian_process.kernels.Hyperparameter.html
So consider the warning as a false positive and ignore it.
Fixes:
```
src/nifreeze/model/gpr.py:291: error: Missing positional arguments "value_type", "name" in call to "Hyperparameter"  [call-arg]
src/nifreeze/model/gpr.py:291: error: Argument 1 to "Hyperparameter" has incompatible type "str"; expected "bool"  [arg-type]
src/nifreeze/model/gpr.py:291: error: Argument 2 to "Hyperparameter" has incompatible type …
```
=> STY: Ignore `Hyperparameter` class instantiation type check.

pyproject.toml, src/nifreeze/data/filtering.py, src/nifreeze/model/dmri.py, test/conftest.py, test/test_filtering.py, test/test_model.py
- FIX: Fix the 4D data generator fixture name
- FIX: Use all provided values in random choice generator fixture
- REF: Refactor filters into `filtering`
Related to #63.
=> REF: Refactor filters into `filtering`

src/nifreeze/data/filtering.py
Use decimals in `float` type arguments for the sake of consistency.
=> STY: Use decimals in `float` type arguments for the sake of consistency

src/nifreeze/data/dmri.py, test/test_data_dmri.py
Add null gradient values to DWI data serialization if appropriate.
When the flag `insert_b0` is `True` the previous implementation prepended the `bzero` attribute data to the `DWI` instance `dataobj`, but it was not adding the corresponding null gradient value to the bval/bvec file pair. This patch set prepends a null gradient to the bval/bvec file pair.
Parameterize the `test_load` testing function to check both cases (i.e. `insert_b0` `False` and `True`).
Add additional checks to ensure that the write/read round-trip works as expected, and that the `bvals` and `bvecs` attributes have the expected values.
Fixes #79.
=> FIX: Revise bzero handling in dMRI data's ``to_nifti()``

test/conftest.py
Call the n-dimensional data generation function from the spatial data generation function for better code reuse.
Fixes the oversight in commit 1495335.
=> REF: Call n-dim data generation function in spatial data generation

scripts/simulate_pet_motion_data.py
Remove unnecessary tildes to document built-in types.
=> DOC: Remove unnecessary tildes to document built-in types

.github/workflows/pythonpackage.yml, .github/workflows/test.yml
Add Python 3.13 to the testing suite and the versions for which the packaging is tested.
Python 3.13 was released in October 2024, and Python 3.14 will be released in October 2025, so it seems reasonable to start testing on Python 3.13.
Release notes:
https://www.python.org/downloads/release/python-3130/
=> TST: Add Python 3.13 to the testing suite

.github/workflows/benchmark.yml, .github/workflows/pythonpackage.yml, .github/workflows/test.yml
Adopt reduced and regular schemes for CI Python build matrix:
- Use Python 3.12 for CI testing and packaging.
- Add a weekly job that uses an extended set of Python versions for testing and packaging.
Change the Python version in the benchmark GHA workflow file to use Python 3.12.
=> MNT: Adopt reduced and regular schemes for CI Python build matrix

src/nifreeze/model/base.py, src/nifreeze/model/dmri.py, src/nifreeze/model/gqi.py
Enables Generalized Q-Imaging to the portfolio of DIPY supported models.
I'm hitting the issue that this model does not have a `predict()` implementation (cc/ @yasseraleman).
```
NotImplementedError: This model does not have prediction implemented yet
```
@arokem, would it be very hard to write?
=> ENH: Add GQI to available models

docs/notebooks/bold_realignment.ipynb
Reuse path variable in BOLD notebook for the sake of compactness.
=> REF: Reuse path variable in BOLD notebook

src/nifreeze/data/pet.py
Remove redundant parentheses when returning a tuple.
Fixes:
```
Remove redundant parentheses
```
raised by the IDE.
=> STY: Remove redundant parentheses when returning a tuple

docs/notebooks/pet_motion_estimation.ipynb
Reorder import statements in PET notebook: import modules close to the statements where they are actually used and remove unused import statements.
Take advantage of the commit to:
- Import only the required `PET` data class from the `nifreeze.data.pet` module
- Use `nb` as the alias of `nibabel` to increase consistency across the code base.
=> REF: Reorder import statements in PET notebook

src/nifreeze/estimator.py
Remove duplicate `NiBabel` import.
Fixes:
```
Shadows name 'nb' from outer scope
```
raised locally by the IDE.
=> STY: Remove duplicate `NiBabel` import

docs/installation.rst
Improve instructions for required external dependencies:
- Remove `DIPY` from the external dependency list: it is listed as a dependency in `pyproject.toml`.
- Add details about how `ANTs` is used and provide the necessary information for a successful installation in the context of `NiFreeze`.
=> DOC: Improve instructions for required external dependencies

src/nifreeze/viz/motion_viz.py
- DOC: Use `:obj:` before `str` so that the type is linked
- DOC: Remove orphan sentence ending word
=> DOC: Miscellaneous documentation fixes

test/test_splitting.py
Remove unnecessary lovo splitting test function docstring: arguments are self-explanatory.
=> DOC: Remove unnecessary lovo splitting test function docstring

docs/notebooks/pet_motion_estimation.ipynb
Use motion corrected frame index consistently in PET notebook: define the index and use it instead of relying in the train, test splits done though the `lofo_split` call, which is also using a different index.
=> FIX: Use motion corrected frame index consistently in PET notebook

src/nifreeze/viz/motion_viz.py
Add missing backtick for inline literal in parameter docstring.
Left behind in commit bfd830e.
=> DOC: Add missing backtick for inline literal in parameter docstring

docs/links.rst, docs/usage.rst
Update the toolkit usage documentation: PR https://github.com/nipreps/nifreeze/pull/62 introduced important changes to the approach that had been used so far within the toolkit. That PR missed to update the usage documentation.
This patch set:
- Expands the first section on importing the `NiFreeze` components to explain at a high-level the components required to run the `NiFreeze` motion estimation.
- Generalizes all passages and make them agnostic to the modality being used as much as possible.
- Updates the instantiation of the `Estimator`, the call to the actual estimation method (`run` instead of `estimate` after the changes introduced in the mentioned PR), and the change in the approach to store the estimated motion parameters (now held by the dataset class instead of being returned …
=> DOC: Update the toolkit usage documentation

README.rst
Remove legacy eddymotion DOI from README file: the package has been revamped significantly since the work referenced by that DOI, has been renamed to `nifreeze` and can be cited through the reference contained in the `CITATION.cff` file.
=> DOC: Remove legacy eddymotion DOI from README file

docs/conf.py
Remove `napoleon` custom section mapping from documentation configuration: as opposed to e.g. `dmriprep`, `fmriprep`, etc. `nifreeze` does not deal with workflows. Thus, no special `Inputs`, `Outputs`, etc. sections need to be mapped. For now, there is no `Attributes` sections either.
=> DOC: Remove `napoleon` custom section mapping from configuration

src/nifreeze/model/dmri.py
- STY: Re-use the lower-bound b and S0 thresholds from dMRI data module
- STY: Define the S0 clipping percentile as a global variable
=> STY: Re-use and define global variables for dMRI model

src/nifreeze/model/base.py, test/test_model.py
Inherit base model class from `ABC` to enforce native abstraction.
Fixes:
```
Abstract methods are allowed in classes whose metaclass is 'ABCMeta'
```
raised locally by the IDE.
=> REF: Inherit base model class from `ABC` to enforce native abstraction

docs/conf.py, docs/usage.rst
Fix API cross-references in usage document:
- Remove the `api/` prefix for `NiFreeze` classes, methods and functions across references, and prefix the paths with tilde to have only the class, method or function of interest name printed.
- Add `NiReports` to the intersphinx mapping so that the `NiReports` functions can be linked properly. Remove the `api/` prefix in those references.
=> DOC: Fix API cross-references in usage document

test/test_analysis.py
Use a local random generator in spike identification test: when using the `random_number_generator` fixture, every time `conftest.py` is modified (even if the seed to the named fixture remains unchanged), the spike indices change, and thus the test fails since the expected indices are hard-coded. Using a local random generator avoids this issue.
The rest of the tests using random data do not rely on particular values being generated, and thus changes to `conftest.py` do not have an effect on them.
Related to
https://github.com/nipreps/nifreeze/pull/181#issuecomment-3111742251 https://github.com/nipreps/nifreeze/pull/160#issuecomment-2954147226
=> TST: Use a local random generator in spike identification test

pyproject.toml, test/conftest.py, test/test_filtering.py
Allow bvals and bvecs to be separate fixtures. The DWI shell selection test was failing in
https://github.com/nipreps/nifreeze/actions/runs/18065201218/job/51406989162#step:11:2848 with
```
if not shellmask.sum():
>           raise RuntimeError(f"Shell corresponding to index {index} (b={bcenter}) is empty.")
E           RuntimeError: Shell corresponding to index 3 (b=2000.0) is empty.
```
When changing `conftest.py` for other purposes, the above test, which was affected since the `bvals` generated by the
`setupt_random_gtab_data` fixture did not match the previous version, and the test's hard-coded expected values no longer matched the existing ones.
Solve the issue by adding two separate fixtures for bvals an bvecs. For the above test bvals will have some fixed values (i.e. will not used …
=> REF: Allow bvals and bvecs to be separate fixtures

src/nifreeze/model/base.py, test/test_model.py
Test trying to instantiate an unsupported model through the factory.
Define the error message as a global variable to be able to check the message in the test.
=> TST: Test trying to instantiate an unsupported model through factory
